######################################################################
# Automatically generated by qmake (2.01a) pt. cze 1 14:35:05 2012
######################################################################

QT += sql
TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp \
    src/qnotes.cpp \
    src/note.cpp

HEADERS += \
    src/qnotes.h \
    src/note.h

FORMS += \
    ui/qnotes.ui
